application:
    storage-path: /home/fileshares-files/files

spring:
  datasource:
#    url: jdbc:postgresql://fileshares-files-db:5432/fileshares_files
    url: jdbc:postgresql://localhost:6870/fileshares_files
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq